### ISSUE TITLE
WTF units!

### ISSUE THREAD

**Issue by JSRoland** [psas/electric-feed-system#3]
### The problem:
Turns out the industry standard for pumps is to use mixed units to run these calculations. but they are terrible to try and figure out what units are actually being used. 
### The solution:
Basically I need more people beating their heads against this. Check out the pump sizing notebook under the  "Alternative approach" section heading and try to figure out what the real conversion coefficients should be to give us real number.

**Comment by Joedang** [comment]
Yeah, wow, you're not kidding. Do you have a book you're going off of for the specific speed calculations? 

As far as I can tell, [the Wikipedia article on it](https://en.wikipedia.org/wiki/Specific_speed#Pump_specific_speed) is self-contradictory. It claims that N_s is nondimensional, which is just wrong. 

```
N_s = n * Q^(1/2) / H^(3/4)
```
Looking at only units:
```
[1] = [cycles]/minute * (m^3/s)^(1/2) / m^(3/4)
[1] = [cycles] * [time]^-1 * 1/60 * [length]^(3/2) * [time]^(1/2) * [length]^(-3/4)
[1] = [cycles] * [time]^(-1/2) * [length]^(3/4)
```
So clearly, the assertion that N_s is nondimensional is like a bunch of grass after it has been grazed upon: BS.

E: Also, protip, you can embed images in markdown like this:
```
![mouse-over text](my_image.jpg)
```
which is a bit easier than using `IPython.display.Image`.

E2: I'm assuming you're talking about [this notebook](https://github.com/psas/electric-feed-system/blob/master/Analysis/electric_pump_calcs/pump_sizing.ipynb).

**Comment by 7deeptide** [comment]
@Joedang This is the modified dimensional form of the specific speed equation, mainly only used in the good 'ol USA. In the rest of the world the equation is made dimensionless by adding $g_0$ to the radical in the denominator.

**Comment by 7deeptide** [comment]
The unit issues are sorted out. Issue closed.
