### ISSUE TITLE
EEs tell us if this motor is a terrible idea.

### ISSUE THREAD

**Issue by JSRoland** [psas/electric-feed-system#4]
### The Problem:
We are a bunch of MEs and thus don't have that much intuition about these types of thing

### How to help:
Check out this motor:
https://hobbyking.com/en_us/turnigy-aquastar-t20-3t-730kv-1280kv-water-cooled-brushless-motor.html

Contact Jorden at: jroland@pdx.edu and tell me why you think this motor will work or why it won't 

### Some context:
We will likely need a brushless DC motor that can deliver 3-4 kW at up to 50000 RPM. Slightly lower requirements can be dealt with.  really we just want an idea of weather or not this is a bad choice of motor.

**Comment by 7deeptide** [comment]
@JSRoland We have the motor and will see how it does. Issue closed.
